version: '2.0'

services:
  ca0:
    container_name: ca0
    image: hyperledger/fabric-ca:x86_64-1.0.0-beta
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org.chained-voting.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ddb9205c44f6bf0cb5307d3b990752621d444d9a4062ec3ff05ae393d558ee17_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org.chained-voting.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/ddb9205c44f6bf0cb5307d3b990752621d444d9a4062ec3ff05ae393d558ee17_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org.chained-voting.com/ca/:/etc/hyperledger/fabric-ca-server-config

  orderer.chained-voting.com:
    container_name: orderer.chained-voting.com
    image: hyperledger/fabric-orderer:x86_64-1.0.0-beta
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/genesis.block
    - ./crypto-config/ordererOrganizations/chained-voting.com/orderers/orderer.chained-voting.com/msp:/var/hyperledger/orderer/msp
    - ./crypto-config/ordererOrganizations/chained-voting.com/orderers/orderer.chained-voting.com/tls:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050

  peer0.org.chained-voting.com:
    container_name: peer0.org.chained-voting.com
    image: hyperledger/fabric-peer:x86_64-1.0.0-beta
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=chainedvoting_default
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_NEXT=true
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.org.chained-voting.com
      - CORE_PEER_ADDRESS=peer0.org.chained-voting.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org.chained-voting.com:7051
      - CORE_PEER_LOCALMSPID=OrgMSP
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start --peer-defaultchain=false
    volumes:
    - /var/run/:/host/var/run/
    - ./crypto-config/peerOrganizations/org.chained-voting.com/peers/peer0.org.chained-voting.com/msp:/etc/hyperledger/fabric/msp
    - ./crypto-config/peerOrganizations/org.chained-voting.com/peers/peer0.org.chained-voting.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7053:7053

  cli:
    container_name: cli
    image: hyperledger/fabric-peer:x86_64-1.0.0-beta
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org.chained-voting.com:7051
      - CORE_PEER_LOCALMSPID=OrgMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org.chained-voting.com/peers/peer0.org.chained-voting.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org.chained-voting.com/peers/peer0.org.chained-voting.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org.chained-voting.com/peers/peer0.org.chained-voting.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org.chained-voting.com/users/Admin@org.chained-voting.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c './scripts/script.sh default; while true; do sleep 20; done'
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.chained-voting.com
      - peer0.org.chained-voting.com
      
  server:
    container_name: server
    build: server
    working_dir: /usr/src/app
    command: bash -c "sleep 800000" 
    volumes:
      - ./server/:/usr/src/app
    depends_on:
      - ca0
      - orderer.chained-voting.com
      - peer0.org.chained-voting.com

  client:
    container_name: client
    build: client
    working_dir: /usr/src/app
    command: bash -c "ng lint && ng serve --host 0.0.0.0"
    volumes:
      - ./client/:/usr/src/app
    depends_on:
      - server
    ports:
      - "4200:4200"